#!/usr/bin/env node
'use strict'

var LamassuConfig = require('lamassu-config')

var config = new LamassuConfig()

updateDb(function (err) {
    if (err) throw err
    console.log('\nSuccess.')
})

function updateDb (callback) {
  var newConfig = {
    exchanges: {
      plugins: {
        current: {
          ticker: 'kraken'
        }
      }
    }
  }
  config.mergeConfig(newConfig, callback)
}
